"""Reseau multi-tetes, pertes, entrainement, inference (etape 6-7 du plan directeur)."""

from .dataset import ObservationDataset
from .features import FEATURE_SIZE, observation_features
from .losses import LossBreakdown, LossWeights, compute_loss, masked_q_loss, soft_cross_entropy
from .network import SongoNet
from .srn_graph import (
    BASE_RELATIONS,
    GLOBAL_FEATURE_DIM,
    NODE_FEATURE_DIM,
    NUM_NODES,
    SongoGraph,
    SongoGraphBatch,
    SongoGraphBuilder,
)
from .srn_network import (
    RelationalBlock,
    SRNConfig,
    SongoRelationalNetwork,
    mask_policy_logits,
    masked_policy_cross_entropy,
    policy_probabilities,
)
from .srn_dataset import (
    DRLDataset,
    DRLSplit,
    SRNBatchCollator,
    SRNTrainingBatch,
    split_examples_by_game_id,
    split_examples_by_fixed_game_ids,
)
from .srn_training import (
    LoadedSRNCheckpoint,
    SRNEpochMetrics,
    SRNEpochRecord,
    SRNLossBreakdown,
    SRNTrainingConfig,
    SRNTrainingResult,
    compute_srn_loss,
    evaluate_srn,
    load_srn_checkpoint,
    make_srn_loader,
    set_training_seed,
    train_srn_epoch,
    train_srn_from_d_rl,
)
from .large_scale_training import (
    SourceAwareSchedule,
    deterministic_epoch_indices,
    split_bucket,
    split_game_ids,
    split_physical_hashes,
    verify_value_sources,
)
from .inference import load_model, make_network_agent
from .registry import (
    ModelManifest,
    build_manifest,
    get_champion,
    list_versions,
    load_registry,
    promote_version,
    register_model,
    save_registry,
    train_and_register,
)
from .train import EpochMetrics, train_model, train_overfit

__all__ = [
    "ObservationDataset",
    "FEATURE_SIZE",
    "observation_features",
    "LossBreakdown",
    "LossWeights",
    "compute_loss",
    "masked_q_loss",
    "soft_cross_entropy",
    "SongoNet",
    "BASE_RELATIONS",
    "GLOBAL_FEATURE_DIM",
    "NODE_FEATURE_DIM",
    "NUM_NODES",
    "SongoGraph",
    "SongoGraphBatch",
    "SongoGraphBuilder",
    "RelationalBlock",
    "SRNConfig",
    "SongoRelationalNetwork",
    "mask_policy_logits",
    "masked_policy_cross_entropy",
    "policy_probabilities",
    "DRLDataset",
    "DRLSplit",
    "SRNBatchCollator",
    "SRNTrainingBatch",
    "split_examples_by_game_id",
    "split_examples_by_fixed_game_ids",
    "LoadedSRNCheckpoint",
    "SRNEpochMetrics",
    "SRNEpochRecord",
    "SRNLossBreakdown",
    "SRNTrainingConfig",
    "SRNTrainingResult",
    "compute_srn_loss",
    "evaluate_srn",
    "load_srn_checkpoint",
    "make_srn_loader",
    "set_training_seed",
    "train_srn_epoch",
    "train_srn_from_d_rl",
    "SourceAwareSchedule",
    "deterministic_epoch_indices",
    "split_bucket",
    "split_game_ids",
    "split_physical_hashes",
    "verify_value_sources",
    "EpochMetrics",
    "train_model",
    "train_overfit",
    "load_model",
    "make_network_agent",
    "ModelManifest",
    "build_manifest",
    "get_champion",
    "list_versions",
    "load_registry",
    "promote_version",
    "register_model",
    "save_registry",
    "train_and_register",
]
