#!/usr/bin/env python3
"""Matérialise le design G4 du Lot 33; aucune génération ni optimisation."""
from pathlib import Path
import json
from songo_ai.training import validate_g4_design

OUT=Path("data/experiments/lot33_g4_design")
G2="data/experiments/lot12_g2_seed_20261200/training/best_validation_checkpoint.pt"
G3P="data/experiments/lot26_g3_scale/checkpoints/g3_strategic_best.pt"
V28="data/experiments/lot28_value_search/checkpoints/v28_a_best.pt"

def write(name,value):
 path=OUT/name;path.parent.mkdir(parents=True,exist_ok=True);path.write_text(json.dumps(value,indent=2,sort_keys=True)+"\n")

def main():
 design={"new_generation_games":8000,"generation_ratio":{"G2_G2":10.,"G3_G3":10.,"G2_G3":80.},"training_source_ratio":{"NEW_GENERATION":70.,"HISTORICAL_RL":20.,"AUTONOMOUS_REANALYSIS":10.},"policy_objective":"MASKED_SOFT_TARGET_CE_TO_PI_MCTS","value_objective":"MSE_TO_TRUE_TERMINAL_Z_ONLY","max_policy_candidates":2,"max_value_candidates":2,"max_policy_value_combinations":4,"opponents":["G2","G3_VALUE_REWORK"],"official_champion":"G2","g3_promoted":False,"training":{"control_updates":32000,"pool_updates":32000}}
 validate_g4_design(design)
 generation={"mode":"CROSSPLAY_ENRICHED_OPERATIONAL_BASELINE","optimality_claim":False,"games":8000,"matchups":{"G2_G2":800,"G3_G3":800,"G2_G3":6400,"crossplay_G2_P1":3200,"crossplay_G3_P1":3200},"search":{"simulations":64,"c_puct":1.5,"root_noise":True,"dirichlet_alpha":.3,"dirichlet_epsilon":.25,"temperature_until_ply":30,"max_plies":400,"repetition_limit":3},"seed_set":"LOT34_G4_GENERATION_V1_TO_BE_FROZEN_BEFORE_RUN","provenance_required":True,"terminal_z_only":True,"truncated_policy_allowed":True,"truncated_value_forbidden":True}
 composition={"ratios":design["training_source_ratio"],"new_generation":{"games":8000,"ratio":design["generation_ratio"]},"historical_rl":{"retained":True,"sources":["D_SELFPLAY_LARGE","prior_autonomous_D_RL"],"teacher_labels":False,"sampling":"generation-balanced before source mixing"},"autonomous_reanalysis":{"retained":True,"physical_positions":40000,"targets":80000,"same_states_reanalyzed_by":["G2","G3_VALUE_REWORK"],"per_model_positions":40000,"mcts_simulations":128,"root_noise":False,"policy_only":True,"teacher_annotations_used":False},"D_REAL_role":"external strategic test only","D_TEACHER_role":"physical-state reservoir only; annotations forbidden","strategic_qdiag_role":"evaluation only, never baseline fuel"}
 replay={"name":"GENERATION_BALANCED_SOURCE_STRATIFIED","batch_size":256,"source_slots":{"NEW_GENERATION":179,"HISTORICAL_RL":51,"AUTONOMOUS_REANALYSIS":26},"new_generation_subslots":{"G2_G2":18,"G3_G3":18,"G2_G3":143},"rounding":"deterministic rotating remainder so long-run ratios equal 70/20/10 and 10/10/80","historical_generation_balancing":"equal generation quota before replacement sampling","value_sampling":"only examples with true terminal z","policy_sampling":"all examples with legal visit counts","strategic_disagreement_oversampling":False,"reason":"Lot32 disagreement is diversity, not an oracle"}
 training={"architecture":"unchanged SRN","initial_policy":{"component":"G3_STRATEGIC","checkpoint":G3P},"initial_value":{"component":"V28_A","checkpoint":V28},"optimizer":"AdamW","learning_rate":.0003,"weight_decay":.0001,"gradient_clip_norm":1.,"batch_size":256,"updates":32000,"schedule":"constant learning rate; fixed update budget","checkpoint_every_updates":4000,"validation_every_updates":4000,"training_seeds":{"CONTROL_G4":20263401,"POOL_G4":20263402,"replication":"one predeclared independent replication only if primary conclusion is statistically indeterminate"},"no_early_stopping_for_arm_comparability":True,"control_and_pool_equal_budget":True}
 policy={"objective":"masked soft-target cross-entropy to pi_MCTS reconstructed from raw visit counts","formula":"L_policy=-sum_a pi_MCTS(a|s) log p_theta(a|s)","illegal_actions_masked":True,"one_hot_replacement":False,"source_provenance_required":True,"special_ranking_loss":False,"reason":"change data distribution only; correction/preservation are selection metrics, not new targets"}
 value={"objective":"mean squared error to true terminal z in player-to-move perspective","formula":"L_value=(v_theta(s)-z_terminal)^2","allowed_sources":["G2_G2 terminal","G3_G3 terminal","G2_G3 terminal","historical terminal RL"],"forbidden_sources":["truncated games","autonomous reanalysis","Teacher/Minimax/root value","pseudo-z"],"source_balanced":True,"under_search_stability_required":True}
 components={"decoupled":True,"policy_component":"full Policy evaluator including its encoder/trunk","value_component":"independent Value evaluator including its encoder/trunk","max_policy_candidates":2,"max_value_candidates":2,"max_combinations":4,"matrix":["P1+V1","P1+V2","P2+V1","P2+V2"],"selection_order":["offline safety gates","MCTS64 short gate","multi-opponent main evaluation"],"initial_reference":"G3_STRATEGIC + V28_A"}
 checkpoints={"saved_at_updates":[0,4000,8000,12000,16000,20000,24000,28000,32000],"selection_data":"VALIDATION split by game_id","final_test_data":"STRATEGIC_TEST disjoint by game_id/state identity","max_policy_retained":2,"max_value_retained":2,"policy_ranking":["finite CE","no entropy collapse","strategic preservation >=85%","MCTS64 short-gate survival"],"value_ranking":["finite MSE","sign accuracy","calibration","value-under-search stability"],"offline_elimination":{"non_finite":True,"illegal_policy_mass":True,"policy_ce_regression_vs_initial_max":.10,"value_mse_regression_vs_initial_max":.10,"min_strategic_preservation":.85,"min_value_prediction_std":.05},"no_posthoc_epoch_arena_selection":True}
 strategic={"splits":{"TRAIN":.85,"VALIDATION":.10,"STRATEGIC_TEST":.05},"split_unit":"game_id","crossplay_game_atomic":True,"state_identity_disjoint_for_reanalysis":True,"battery":{"G2_G3_disagreement":2000,"historical_autonomous":2000,"D_REAL":575,"structurally_diverse":2000},"teacher_targets":False,"roles":{"VALIDATION":"checkpoint selection","STRATEGIC_TEST":"frozen correction/preservation/calibration diagnostics","ARENA":"playing strength and promotion only"},"qdiag":"targeted diagnostic only"}
 opponents={"opponents":["G2","G3_VALUE_REWORK"],"reason":{"G2":"official champion gate","G3_VALUE_REWORK":"complementary-style forgetting gate"},"paired":True,"side_swapped":True,"report_P1_P2":True,"historical_opponents":[]}
 search_rule={"primary_budgets":[64,128],"budget_256":"confirmation when pooled result is within 3 points of 50%, 64/128 differ by >5 points, or a collapse signal appears","strict_monotonicity_required":False,"robust_when":{"max_replicated_budget_drop":.07,"collapse_must_not_repeat":True,"consider_confidence_intervals":True,"consider_global_trend":True},"collapse_definition":"a >7 percentage-point drop versus another primary budget reproduced with an independent paired opening set"}
 promotion={"champion_progression":{"pooled_score_min":.52,"paired_bootstrap_probability_score_gt_50_min":.95},"population_robustness":{"score_vs_G3_min":.48,"ci95_low_min":.42},"side_balance":{"max_absolute_P1_P2_score_gap":.10},"search_robustness":{"max_replicated_budget_drop":.07,"reproduced_collapse_forbidden":True},"safety":{"strategic_preservation_min":.85,"pathology_forbidden":True},"all_gates_required":True,"individual_budget_ci_low_gt_50_required":False}
 admission={"separate_from_promotion":True,"minimum_pooled_score_vs_champion":.42,"diversity_any":{"strategic_diversity_gain_min":.05,"marginal_data_gain_min":.02},"max_compute_cost_ratio":2.,"pathology_forbidden":True,"requires_future_generation_probe":True,"statuses":["CHAMPION_AND_GENERATOR","GENERATOR_ONLY","REJECTED","INCONCLUSIVE"]}
 control={"CONTROL_G4":{"initialization":"G3_STRATEGIC + V28_A","new_data":"8000 newly generated G2-G2 games","training_mix":"70% new G2-only generation + 20% same historical RL + 10% G2-only autonomous reanalysis","updates":32000},"POOL_G4":{"initialization":"G3_STRATEGIC + V28_A","new_data":"8000 newly generated games at 10/10/80","training_mix":"70% new crossplay-enriched generation + 20% same historical RL + 10% dual-generator autonomous reanalysis","updates":32000},"held_constant":["architecture","initialization","optimizer","learning rate","batch size","updates","MCTS settings","historical reservoir size","reanalysis target count","splits","checkpoint cadence","evaluation"],"causal_variable":"data-generation paradigm","paradigm_value_rule":{"positive_if":"POOL_G4 exceeds CONTROL_G4 by >=3 percentage points on pooled multi-opponent score with paired-bootstrap P(delta>0)>=0.95, or POOL_G4 passes champion promotion while CONTROL_G4 does not","also_required":["no population collapse","search robust","strategic preservation >=85%"]}}
 compute={"basis":"measured Lot32 local throughput; extrapolation, not a machine-independent promise","POOL_G4":{"games":8000,"expected_positions":727752,"expected_mcts_simulations":46576128,"estimated_generation_seconds_local":27766.7,"estimated_generation_hours_local":7.71,"estimated_jsonl_storage_gib":1.20},"CONTROL_G4":{"games":8000,"expected_positions":706744,"expected_mcts_simulations":45231616,"estimated_generation_seconds_local":16890.7,"estimated_generation_hours_local":4.69,"estimated_jsonl_storage_gib":1.06},"dual_reanalysis":{"physical_states":40000,"policy_targets":80000,"mcts_simulations_per_target":128,"estimated_seconds_local_from_lot25":4056.9,"estimated_hours_local":1.13},"total_generation_and_reanalysis_hours_local":13.53,"training_duration":"must be measured by a preflight benchmark; not invented in Lot33"}
 next_action={"G4_DESIGN_VALID":"YES","NEXT_ACTION":"G4_DATA_GENERATION_AND_CONTROLLED_TRAINING","OFFICIAL_CHAMPION":"G2","G3_PROMOTED":"NO","G3_VALUE_REWORK_GENERATOR_STATUS":"RETAIN"}
 report={"lot":33,"nature":"DESIGN_ONLY","training_performed":False,"verdicts":{"G4_DESIGN_VALID":"YES","CROSSPLAY_ENRICHED_GENERATION_SELECTED":"YES","SOURCE_AWARE_TRAINING_REQUIRED":"YES","GENERATION_BALANCED_REPLAY_REQUIRED":"YES","HISTORICAL_DATA_RETAINED":"YES","AUTONOMOUS_REANALYSIS_RETAINED":"YES","STRATEGIC_DISAGREEMENT_OVERSAMPLING":"NO","POLICY_VALUE_SELECTION_DECOUPLED":"YES","MULTI_OPPONENT_EVALUATION_REQUIRED":"YES","STRICT_SEARCH_MONOTONICITY_REQUIRED":"NO","G4_CONTROL_REQUIRED":"YES"},"design":design,"initialization":{"G4_INITIAL_POLICY":"G3_STRATEGIC","G4_INITIAL_VALUE":"V28_A"},"objectives":{"G4_POLICY_OBJECTIVE":design["policy_objective"],"G4_VALUE_OBJECTIVE":design["value_objective"]},"G4_REPLAY_STRATEGY":"GENERATION_BALANCED_SOURCE_STRATIFIED","PRIMARY_SEARCH_BUDGETS":[64,128],"MCTS256":"CONDITIONAL_CONFIRMATION","official_status":next_action}
 for filename,value in (("generation_plan.json",generation),("dataset_composition.json",composition),("replay_strategy.json",replay),("training_protocol.json",training),("policy_protocol.json",policy),("value_protocol.json",value),("component_selection.json",components),("checkpoint_selection.json",checkpoints),("strategic_test_design.json",strategic),("opponent_battery.json",opponents),("search_robustness_rule.json",search_rule),("promotion_rule.json",promotion),("generator_admission_rule.json",admission),("experiment_control.json",control),("compute_budget.json",compute),("next_action.json",next_action),("report.json",report)):write(filename,value)
 print(json.dumps(report["verdicts"]|next_action,indent=2))
if __name__=="__main__":main()
