#!/usr/bin/env python3
"""Lot 30 : matérialise la conception du paradigme autonome, sans entraînement."""
import json
from pathlib import Path
from run_srn_lot12 import write_json

OUT=Path("data/experiments/lot30_paradigm")
PARADIGM="CHAMPION_GATED_DIVERSE_GENERATOR_POOL"

def main():
 OUT.mkdir(parents=True,exist_ok=True)
 comparison={"baseline_cost":"1x single-champion generation","paradigms":[
  {"name":"SINGLE_CHAMPION","diversity":"low","stability":"high locally, stagnation risk","autonomy":"partial","compute_cost":"1.0x","implementation_complexity":"low","forgetting_protection":"low","non_transitivity":"poor","srn_compatibility":"full","fit_lots_14_29":"poor: repeated reject/repair cycles"},
  {"name":"CHAMPION_CHALLENGER","diversity":"medium","stability":"medium","autonomy":"medium","compute_cost":"~1.1-1.3x","implementation_complexity":"low-medium","forgetting_protection":"low-medium","non_transitivity":"limited","srn_compatibility":"full","fit_lots_14_29":"better but retains two-model tunnel"},
  {"name":"OPPONENT_POOL","diversity":"medium-high","stability":"high","autonomy":"high","compute_cost":"~1.2-1.5x","implementation_complexity":"medium","forgetting_protection":"high","non_transitivity":"good","srn_compatibility":"full","fit_lots_14_29":"strong"},
  {"name":"POPULATION_SELFPLAY","diversity":"high","stability":"medium","autonomy":"high","compute_cost":"~1.5-2.5x","implementation_complexity":"high","forgetting_protection":"high","non_transitivity":"good","srn_compatibility":"full","fit_lots_14_29":"useful but currently disproportionate"},
  {"name":"LEAGUE","diversity":"very high","stability":"high if managed","autonomy":"high","compute_cost":">2.5x","implementation_complexity":"very high","forgetting_protection":"very high","non_transitivity":"very good","srn_compatibility":"full","fit_lots_14_29":"unnecessary complexity now"},
  {"name":"GENERATIONAL_MIXTURE","diversity":"medium-high","stability":"high","autonomy":"high","compute_cost":"~1.2-1.6x","implementation_complexity":"medium","forgetting_protection":"high","non_transitivity":"good","srn_compatibility":"full","fit_lots_14_29":"strong"},
  {"name":"POPULATION_DISTILLATION","diversity":"training-only high","stability":"medium-high","autonomy":"medium","compute_cost":"~1.5-2.0x","implementation_complexity":"high","forgetting_protection":"medium","non_transitivity":"medium","srn_compatibility":"full at deployment","fit_lots_14_29":"later option, not first remedy"},
  {"name":PARADIGM,"diversity":"high but bounded","stability":"champion-gated","autonomy":"high","compute_cost":"~1.3-1.7x target, calibrate in pilot","implementation_complexity":"medium","forgetting_protection":"high","non_transitivity":"good","srn_compatibility":"full","fit_lots_14_29":"best balance of observed needs and complexity"}]}
 registry={"statuses":["CHAMPION","GENERATOR","CHALLENGER","HISTORICAL","RETIRED","REJECTED"],"multi_role":True,"immutable_fields":["model_id","checkpoint_hash","architecture_fingerprint","policy_fingerprint","value_fingerprint","lineage"],"mutable_registry_fields":["roles","admission_generation","retirement_generation","evidence_refs"],"current":[{"model_id":"G2","roles":["CHAMPION","GENERATOR","HISTORICAL"],"official_champion":True},{"model_id":"G3_VALUE_REWORK","roles":["REJECTED","GENERATOR"],"official_champion":False,"generator_status":"PROBATIONARY"}],"principle":"REJECTED for champion promotion does not imply useless for generation"}
 pool={"recommended":True,"name":"AUTHORIZED_GENERATOR_POOL","official_champion":"G2","members":[{"model_id":"G2","role":"ANCHOR_CHAMPION"},{"model_id":"G3_VALUE_REWORK","role":"PROBATIONARY_DIVERSITY_GENERATOR"}],"admission":{"gates":["immutable and reproducible identity","no engine/search pathology","credible non-inferiority across multiple budgets","positive or complementary strategic signal","measurable useful diversity","bounded pilot contribution before full admission"],"numeric_thresholds":"calibrated prospectively by pilot; not invented from one candidate"},"removal":{"conditions":["persistent weakness across population","redundancy without incremental state coverage","stale contribution","pathology or reproducibility failure","dominated and no useful diversity"],"bounded_size":"retain champion, recent robust generators and at most a small historical anchor set"},"g3_value_rework_admission":"YES_PROBATIONARY","lot29_unchanged":{"G3_PROMOTED":"NO","OFFICIAL_CHAMPION":"G2"}}
 matchmaking={"strategy":"CHAMPION_ANCHORED_DIVERSITY_AND_UNCERTAINTY_MATCHMAKING","required_match_types":["champion self-play","generator self-play","champion-generator cross-play with side swap","recent-historical cross-play"],"selection_axes":["minimum source quotas","matchup uncertainty","state/trajectory novelty","underrepresented provenance"],"elo_role":"summary and scheduling only, never promotion truth","anti_contamination":["per-source caps","minimum champion anchor quota","exclude persistently weak generators","terminal-z only","source-aware validation"],"pilot_fixed_mix":{"arm_A":{"games":400,"G2_vs_G2":400},"arm_B":{"games":400,"G2_vs_G2":100,"G3_vs_G3":100,"G2_vs_G3_side_balanced":200},"reason":"equal total game budget; half of mixed arm tests the uniquely informative cross-play mechanism; self-play anchors separate source effects"},"future_ratios":"learned from pilot novelty/quality subject to floors and caps; not frozen now"}
 replay={"policy":"GENERATION_STRATIFIED_SLIDING_WINDOW_WITH_HISTORICAL_ANCHORS","active_window":"recent 3 validated data generations initially; tune prospectively","strata":["champion_selfplay","generator_selfplay","crossplay","historical_anchor","reanalysis_unlabeled_value_excluded"],"sampling":"source-balanced first, then diversity-aware within source","value_targets":"terminal z only","policy_targets":"MCTS visit distributions with generator/opponent/budget provenance","history":"small immutable strategic anchors from older generations","teacher_positions":"states may seed coverage/reanalysis only; Teacher labels prohibited","anti_volume_domination":True,"forgetting_controls":["historical holdout arenas","old-generation strata","multi-opponent candidate evaluation"]}
 promotion={"champion_promotion":{"principle":"population robustness, not champion duel alone","required":["valid immutable candidate","positive evidence versus champion","non-regression versus recent historical opponents","acceptable aggregate population score","no major side/search pathology","replication on independent seeds"],"search_robustness":"joint interpretation of paired CIs, effect sizes and repeated budgets; strict monotonicity not required; collapse means replicated material negative shift, not one point estimate dip","prospective_calibration_required":True},"generator_admission":{"strictness":"weaker than champion promotion","purpose":"data diversity","probationary_first":True},"component_selection":{"partially_decoupled":True,"procedure":"maintain bounded Policy and Value candidates, assemble a small predeclared cross-product, require Policy identity and evaluate resulting agents under MCTS","deployment":"one compact SRN-compatible agent plus MCTS","no_unbounded_component_league":True}}
 pilot={"name":"GENERATOR_POOL_PILOT_V1","training":False,"mcts_budget":64,"arms":{"G2_ONLY":{"games":400,"matchups":{"G2_G2":400}},"POOL":{"games":400,"matchups":{"G2_G2":100,"G3_G3":100,"G2_G3_crossplay":200}}},"fixed_before_generation":True,"same_global_game_budget":True,"seeds":"new immutable pilot seed manifest","primary_question":"does the pool produce more diverse and strategically useful data than G2-only?","metrics":["unique states","new states vs D_SCALE_V1","state overlap","trajectory diversity","action diversity","terminal distribution","game length","cross-play-only states","strategic disagreement states","source-conditioned truncation/pathology"],"success":"higher useful novelty/coverage without weak-source pathology or terminal-target invalidity","no_candidate_training":True}
 next_cycle={"paradigm":PARADIGM,"steps":["freeze registries and generation manifest","mixed self-play plus cross-play","validate provenance and terminal z","generation/source-stratified replay insertion","source-balanced Policy/Value training","bounded component candidate assembly","multi-opponent evaluation","separate champion promotion and generator admission","retire redundant/stale generators","repeat"],"candidate_output":"single compact Policy-Value agent for Unity/mobile","human_role":"pre-register protocols and budgets, not invent per-generation corrections","success_metrics":["autonomous improvement","useful strategic diversity","population robustness","search robustness","historical robustness","data novelty","reproducibility"]}
 verdict={"CURRENT_SINGLE_CHAMPION_PARADIGM_ADEQUATE":"PARTIAL","GENERATOR_POOL_RECOMMENDED":"YES","POPULATION_TRAINING_RECOMMENDED":"YES","CROSS_PLAY_RECOMMENDED":"YES","HISTORICAL_OPPONENTS_RECOMMENDED":"YES","POLICY_VALUE_SELECTION_SHOULD_BE_PARTIALLY_DECOUPLED":"YES","PROMOTION_SHOULD_BE_MULTI_OPPONENT":"YES","STRICT_SEARCH_MONOTONICITY_REQUIRED":"NO","RECOMMENDED_LEARNING_PARADIGM":PARADIGM,"OFFICIAL_CHAMPION":"G2","G3_PROMOTED":"NO","G3_VALUE_REWORK_GENERATOR_ADMISSION":"YES","NEXT_ACTION":"GENERATOR_POOL_PILOT"}
 risks={"population_drift":"champion anchor quotas and independent external holdouts","weak_model_contamination":"probation, source caps and removal gates","compute_explosion":"bounded pool and no full league","cyclic_strategies":"historical cross-play and population matrix","stale_opponents":"novelty-based retirement","dataset_imbalance":"source-balanced sampler","catastrophic_forgetting":"historical replay anchors and multi-opponent evaluation"}
 for name,data in (("paradigm_comparison",comparison),("model_registry_design",registry),("generator_pool_design",pool),("matchmaking_design",matchmaking),("replay_strategy",replay),("promotion_framework",promotion),("pilot_design",pilot),("next_cycle_design",next_cycle)):write_json(OUT/f"{name}.json",data)
 write_json(OUT/"report.json",{"lot":30,"training_performed":False,"large_selfplay_performed":False,"strength_matrix_executed":False,"diversity_matrix_executed":False,"reason_no_matrix":"existing Lots 26-29 already establish champion-relative force; next discriminating experiment is equal-budget data-generation pilot","paradigm":PARADIGM,"verdict":verdict,"risks":risks,"artifacts":[x.name for x in OUT.glob("*.json")]})
 print(json.dumps(verdict,indent=2))
if __name__=="__main__":main()
