#!/usr/bin/env python3
"""Lot 35: champion identity gate before generator-pool diagnostics."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
from songo_ai.model import load_srn_checkpoint
from run_srn_lot12 import sha256,write_json
from run_srn_lot32 import G2,G3P,V28

OUT=Path("data/experiments/lot35_generator_pool");L34=Path("data/experiments/lot34r_g4_retry")

def composite(policy,value):return hashlib.sha256(f"{sha256(policy)}:{sha256(value)}".encode()).hexdigest()
def architecture_fingerprint(path):
 c=load_srn_checkpoint(path).model.config
 raw=json.dumps(c.__dict__ if hasattr(c,"__dict__") else str(c),sort_keys=True,default=str).encode();return hashlib.sha256(raw).hexdigest()
def candidate(name,policy,value,source,metrics):return {"model_id":name,"generation":4,"original_source":source,"policy_checkpoint":str(policy),"value_checkpoint":str(value),"policy_fingerprint":sha256(policy),"value_fingerprint":sha256(value),"model_fingerprint":composite(policy,value),"architecture_fingerprint":architecture_fingerprint(policy),"promotion_metrics":metrics,"promotion_rule_passed":True}

def main():
 OUT.mkdir(parents=True,exist_ok=True);promotion=json.load((L34/"promotion_decision.json").open());finalists=json.load((L34/"finalist_selection.json").open());report=json.load((L34/"report.json").open());rule=json.load(Path("data/experiments/lot33_g4_design/promotion_rule.json").open())
 models={arm:candidate(f"{arm}_G4R",Path(finalists[arm]["policy"]["path"]),Path(finalists[arm]["value"]["path"]),arm,promotion["metrics"][arm]) for arm in ("CONTROL","POOL")};direct=report["scores"]["pool_vs_control"]
 ambiguity={"both_pass_promotion_rule":promotion["CONTROL"]["promoted"] and promotion["POOL"]["promoted"],"promotion_rule_has_unique_tiebreak":False,"lot34r_report_names_unique_source":False,"direct_head_to_head":{"POOL_score_MCTS64":direct["64"],"POOL_score_MCTS128":direct["128"],"conclusive":False}}
 identity={"G4_CHAMPION_IDENTITY_RESOLVED":"NO","reason":"Both CONTROL_G4R and POOL_G4R pass every pre-registered promotion gate; Lot33 defines no tie-break and Lot34R records only the generic alias G4.","candidates":models,"ambiguity_evidence":ambiguity,"official_alias":"G4 (source unresolved)","G4_CHAMPION_SOURCE":None,"G4_CHAMPION_POLICY_CHECKPOINT":None,"G4_CHAMPION_VALUE_CHECKPOINT":None,"G4_CHAMPION_POLICY_FINGERPRINT":None,"G4_CHAMPION_VALUE_FINGERPRINT":None,"no_posthoc_choice":True,"resolution_procedure":{"status":"PRE_REGISTERED_NOT_EXECUTED","stage_1":"1024 paired side-swapped games CONTROL_G4R vs POOL_G4R at MCTS128 with independent seed 20263501","stage_1_decision":"select a model only if paired bootstrap P(score>50%) >= .95","stage_2_if_inconclusive":"1024 paired side-swapped games at MCTS256 with independent seed 20263502","stage_2_decision":"same .95 paired-bootstrap rule","terminal_if_still_inconclusive":"keep identity unresolved and require an explicit governance decision; never infer a winner from isolated offline metrics"}};write_json(OUT/"g4_champion_identity.json",identity)
 protocol_hash=hashlib.sha256((sha256(L34/"configuration.json")+sha256(L34/"retry_intervention.json")).encode()).hexdigest();datasets=json.load((L34/"lot34_dataset_identity.json").open())
 registry={"version":"LOT35_PROVISIONAL","valid":False,"blocked_by":"G4_CHAMPION_IDENTITY_UNRESOLVED","lineage":["G2","G3_STRATEGIC_POLICY","V28_A_VALUE_REPAIR","G4_INITIALIZATION","CORRECT_AND_PRESERVE","G4_PROMOTION_ALIAS_UNRESOLVED"],"models":{"G2":{"generation":2,"roles":["HISTORICAL_OPPONENT"],"policy_checkpoint":str(G2),"value_checkpoint":str(G2),"fingerprint":sha256(G2)},"G3_VALUE_REWORK":{"generation":3,"roles":["HISTORICAL_OPPONENT"],"policy_checkpoint":str(G3P),"value_checkpoint":str(V28),"policy_fingerprint":sha256(G3P),"value_fingerprint":sha256(V28)},"CONTROL_G4R":{**models["CONTROL"],"roles":["PROBATIONARY_GENERATOR"]},"POOL_G4R":{**models["POOL"],"roles":["PROBATIONARY_GENERATOR"]}},"training_dataset_fingerprints":{"CONTROL":datasets["CONTROL"]["data"]["sha256"],"POOL":datasets["POOL"]["data"]["sha256"]},"training_protocol_fingerprint":protocol_hash};write_json(OUT/"model_registry.json",registry)
 thresholds={"pre_registered_before_diagnostic_trajectories":True,"material_state_contribution_min":.02,"material_strategic_disagreement_min":.05,"high_redundancy_overlap_min":.95,"maximum_relative_compute_cost":1.5,"minimum_generator_score_vs_champion":.20,"max_active_generators":3,"state_coverage_not_mandatory_if_strategic_contribution_material":True}
 config={"lot":35,"training_performed":False,"massive_g5_generation_performed":False,"engine_modified":False,"srn_modified":False,"mcts_modified":False,"max_active_generators":3,"thresholds":thresholds,"identity_gate_required":True,"identity_gate_passed":False};write_json(OUT/"configuration.json",config);write_json(OUT/"population_candidates.json",{"candidates":["G2","G3_VALUE_REWORK","CONTROL_G4R","POOL_G4R"],"evaluation_status":"BLOCKED_BY_IDENTITY"})
 plan={"status":"NOT_EXECUTED_IDENTITY_GATE_CLOSED","diagnostic_games_per_source":512,"mcts_budget":64,"c_puct":1.5,"side_balanced":True,"baseline":"G4_CHAMPION_SELFPLAY","planned_pairs":["G4_CHAMPION_SELFPLAY","G4_CHAMPION_G2","G4_CHAMPION_G3_VALUE_REWORK","G4_CHAMPION_G4_ALTERNATE"],"thresholds":thresholds,"not_d_g5":True};write_json(OUT/"diagnostic_generation_plan.json",plan)
 blocked={"status":"NOT_RUN","reason":"G4_CHAMPION_IDENTITY_RESOLVED=NO"}
 for name in ("diagnostic_generation_report","pairwise_diversity","marginal_state_contribution","marginal_strategic_contribution","redundancy_analysis","saturation_analysis","compute_cost","generator_utility","pruning_decision"):write_json(OUT/f"{name}.json",blocked)
 pool={"version":"GENERATOR_POOL_V2_PROVISIONAL","valid":False,"MAX_ACTIVE_GENERATORS":3,"ACTIVE_GENERATOR_POOL":[],"HISTORICAL_OPPONENT_POOL":["G2","G3_VALUE_REWORK"],"RETIRED_MODELS":[],"blocked_by":"unique champion identity required","champion_always_active_contract":True};write_json(OUT/"generator_pool_v2.json",pool)
 design={"status":"BLOCKED_BY_IDENTITY","G5_GENERATION_MODE":None,"G5_GENERATION_RATIOS":None,"G5_INITIAL_POLICY":"G4_CHAMPION_POLICY (fingerprint unresolved)","G5_INITIAL_VALUE":"G4_CHAMPION_VALUE (fingerprint unresolved)","G5_POLICY_OBJECTIVE":"CORRECT_AND_PRESERVE","G5_VALUE_OBJECTIVE":"MSE_TO_TRUE_TERMINAL_Z_ONLY","POLICY_VALUE_SELECTION_DECOUPLED":"YES","G5_TRAINING_PERFORMED":"NO","G5_MASSIVE_DATA_GENERATION_PERFORMED":"NO"};write_json(OUT/"g5_generation_design.json",design);next_action={"NEXT_ACTION":"G4_CHAMPION_IDENTITY_RESOLUTION","justification":"A valid immutable generator pool cannot reference an unresolved champion fingerprint."};write_json(OUT/"next_action.json",next_action)
 verdict={"G4_CHAMPION_IDENTITY_RESOLVED":"NO","G4_CHAMPION_SOURCE":"UNRESOLVED","G2_ACTIVE_GENERATOR":"INCONCLUSIVE","G2_HISTORICAL_OPPONENT":"YES","G2_MARGINAL_STRATEGIC_CONTRIBUTION":"INCONCLUSIVE","G2_REDUNDANCY_WITH_G4":"INCONCLUSIVE","G3_ACTIVE_GENERATOR":"INCONCLUSIVE","G3_HISTORICAL_OPPONENT":"YES","G3_MARGINAL_STRATEGIC_CONTRIBUTION":"INCONCLUSIVE","G3_REDUNDANCY_WITH_G4":"INCONCLUSIVE","G3_PROMOTED":"NO","G4_ALTERNATE_ACTIVE_GENERATOR":"INCONCLUSIVE","G4_ALTERNATE_HISTORICAL_OPPONENT":"INCONCLUSIVE","G4_ALTERNATE_MARGINAL_STRATEGIC_CONTRIBUTION":"INCONCLUSIVE","G4_ALTERNATE_REDUNDANCY_WITH_CHAMPION":"INCONCLUSIVE","ACTIVE_GENERATOR_POOL":[],"HISTORICAL_OPPONENT_POOL":["G2","G3_VALUE_REWORK"],"RETIRED_MODELS":[],"MAX_ACTIVE_GENERATORS":3,"G5_GENERATION_MODE":"UNRESOLVED","G5_GENERATION_RATIOS":None,"G5_TRAINING_PERFORMED":"NO","G5_MASSIVE_DATA_GENERATION_PERFORMED":"NO","OFFICIAL_CHAMPION":"G4_ALIAS_IDENTITY_UNRESOLVED","NEXT_ACTION":next_action["NEXT_ACTION"]};write_json(OUT/"report.json",{"lot":35,"status":"BLOCKED_AT_CHAMPION_IDENTITY_GATE","identity":identity,"promotion_rule_fingerprint":sha256(Path("data/experiments/lot33_g4_design/promotion_rule.json")),"verdict":verdict});print(json.dumps(verdict,indent=2))
if __name__=="__main__":main()
